### ISSUE TITLE
Name display error of RTS

### ISSUE THREAD

**Issue by NachuanWang** [Gaohaoyang/pte-crx#7]
should it be RL instead?

**Comment by NachuanWang** [comment]
just change the variable in scorelist.ts

**Comment by Gaohaoyang** [comment]
Yes, you are right. I am working on it.

As you know, the PTE includes both Core and Academic versions. There is an RTS in Core, but an RL in Academic.

I will distinguish between Core and Academic so that different test types display the appropriate sub-score names.
